package Interfaces;


import Interfaces.CrearCuenta;
import java.awt.Color;








/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikv
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xMouse;
    int yMouse;
    Color grisClaro = new Color(176,176,176);
    Color grisOscuro = new Color(85,84,84);

    public Login() {
        initComponents();
       this.setLocationRelativeTo(null);       
       Usuario1.setBackground(new java.awt.Color(0,0,0,1));
       Cerrar.setBackground(new java.awt.Color(0,0,0,1));
       Header.setBackground(new java.awt.Color(0,0,0,1));
       PasswordJField.setBackground(new java.awt.Color(0,0,0,1));
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Usuario1 = new javax.swing.JTextField();
        PasswordJField = new javax.swing.JPasswordField();
        TermsAndConditions = new javax.swing.JLabel();
        BirdWatch = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        UsuarioBox = new javax.swing.JLabel();
        ContrasenaBox = new javax.swing.JLabel();
        IniciarSesionButton = new javax.swing.JButton();
        SinCuenta = new javax.swing.JButton();
        Cerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Content.setMaximumSize(new java.awt.Dimension(1280, 832));
        Content.setMinimumSize(new java.awt.Dimension(1280, 832));
        Content.setPreferredSize(new java.awt.Dimension(1280, 832));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Content.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 40));

        Usuario1.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(176, 176, 176));
        Usuario1.setText("Usuario");
        Usuario1.setToolTipText("Usuario");
        Usuario1.setBorder(null);
        Usuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Usuario1.setSelectionColor(new java.awt.Color(0, 204, 0));
        Usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Usuario1MouseClicked(evt);
            }
        });
        Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario1ActionPerformed(evt);
            }
        });
        Usuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Usuario1KeyPressed(evt);
            }
        });
        Content.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 285, 332, 30));

        PasswordJField.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        PasswordJField.setForeground(new java.awt.Color(176, 176, 176));
        PasswordJField.setText("**********");
        PasswordJField.setToolTipText("Contrase?a");
        PasswordJField.setBorder(null);
        PasswordJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordJFieldMouseClicked(evt);
            }
        });
        PasswordJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordJFieldActionPerformed(evt);
            }
        });
        PasswordJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordJFieldKeyPressed(evt);
            }
        });
        Content.add(PasswordJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 387, 332, 30));

        TermsAndConditions.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        TermsAndConditions.setForeground(new java.awt.Color(255, 255, 255));
        TermsAndConditions.setText("Provacy policy and terms of service");
        TermsAndConditions.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Content.add(TermsAndConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 331, 52));

        BirdWatch.setFont(new java.awt.Font("Jockey One", 0, 64)); // NOI18N
        BirdWatch.setForeground(new java.awt.Color(255, 255, 255));
        BirdWatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirdWatch.setText("BIRDWATCH");
        BirdWatch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Content.add(BirdWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 390, 340, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Green Gradient Background.png"))); // NOI18N
        Content.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 641, 832));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Birdwatch Login.png"))); // NOI18N
        Content.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 55, 122, 126));

        UsuarioBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Usuario Box.png"))); // NOI18N
        Content.add(UsuarioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 276, 440, 49));

        ContrasenaBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password Box.png"))); // NOI18N
        Content.add(ContrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 378, 440, 49));

        IniciarSesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Iniciar Sesion Button.png"))); // NOI18N
        IniciarSesionButton.setBorder(null);
        IniciarSesionButton.setBorderPainted(false);
        IniciarSesionButton.setContentAreaFilled(false);
        IniciarSesionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionButtonActionPerformed(evt);
            }
        });
        Content.add(IniciarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 502, 412, 65));

        SinCuenta.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        SinCuenta.setForeground(new java.awt.Color(0, 99, 249));
        SinCuenta.setText("?A?n no tienes cuenta? Haz click aqu?.");
        SinCuenta.setBorder(null);
        SinCuenta.setBorderPainted(false);
        SinCuenta.setContentAreaFilled(false);
        SinCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinCuentaActionPerformed(evt);
            }
        });
        Content.add(SinCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 593, -1, -1));

        jLabel1.setFont(new java.awt.Font("Inter Thin", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jTextField1.setText("jTextField1");
        Content.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
        String usuario = Usuario1.getText();
        String password = String.copyValueOf(PasswordJField.getPassword());
        
        
        
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void SinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinCuentaActionPerformed
       this.setVisible(false);
       CrearCuenta cC = new CrearCuenta();
       cC.setVisible(true);
    }//GEN-LAST:event_SinCuentaActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void PasswordJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordJFieldActionPerformed

    private void PasswordJFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordJFieldKeyPressed
        
    }//GEN-LAST:event_PasswordJFieldKeyPressed

    private void PasswordJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordJFieldMouseClicked
        if (Usuario1.getText().isEmpty()) {
            Usuario1.setText("Usuario");
        Usuario1.setForeground(grisClaro);
        }
        
        if (String.valueOf(PasswordJField.getPassword()).equals("**********")) {
            PasswordJField.setText("");
        PasswordJField.setForeground(grisOscuro);
        }
        
    }//GEN-LAST:event_PasswordJFieldMouseClicked

    private void Usuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Usuario1KeyPressed

    }//GEN-LAST:event_Usuario1KeyPressed

    private void Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario1ActionPerformed

    private void Usuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usuario1MouseClicked
        if(Usuario1.getText().equals("Usuario")){
            Usuario1.setText("");
            Usuario1.setForeground(grisOscuro);
        }
        if(String.valueOf(PasswordJField.getPassword()).isEmpty()){
            PasswordJField.setText("**********");
            PasswordJField.setForeground(grisClaro);
        }
    }//GEN-LAST:event_Usuario1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BirdWatch;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel ContrasenaBox;
    private javax.swing.JPanel Header;
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PasswordJField;
    private javax.swing.JButton SinCuenta;
    private javax.swing.JLabel TermsAndConditions;
    private javax.swing.JTextField Usuario1;
    private javax.swing.JLabel UsuarioBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
